site_name: dog_breed_classifier
site_author: Group 45
docs_dir: source

theme:
  language: en
  name: material
  features:
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Viewer: viewer.md
  - About: about.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
